-- ============================================================
-- SMS 고객 마스터 테이블 (DBA 검토 후 적용)
-- 목적: /sms/customer-search (고객별 조회) 화면의 기준 마스터.
--       기존 SMS.SMS_HISTORY 에는 고객 식별이 수신번호(RECEIVER_NO) 뿐이므로
--       고객 단위 집계/마케팅 동의/메모를 보관하기 위한 업무 마스터.
-- 주의: MOBILE_NO, EMAIL, BIRTH_DT 는 개인정보. 화면/로그 마스킹 정책 적용.
-- ============================================================

CREATE TABLE SMS.CUSTOMER (
    CUSTOMER_ID     NUMBER GENERATED ALWAYS AS IDENTITY,
    CUSTOMER_NM     VARCHAR2(100 CHAR)  NOT NULL,
    MOBILE_NO       VARCHAR2(20)        NOT NULL,
    EMAIL           VARCHAR2(200 CHAR),
    BIRTH_DT        VARCHAR2(8),            -- YYYYMMDD
    GENDER_CD       VARCHAR2(1),             -- M / F / U(알수없음)
    AGREE_YN        VARCHAR2(1)         DEFAULT 'N' NOT NULL,  -- Y/N 마케팅 수신 동의
    AGREE_DT        TIMESTAMP(6),
    MEMO            VARCHAR2(1000 CHAR),
    USE_YN          VARCHAR2(1)         DEFAULT 'Y' NOT NULL,
    REG_ID          VARCHAR2(12)        NOT NULL,
    REG_DTTM        TIMESTAMP(6)        DEFAULT SYSTIMESTAMP NOT NULL,
    UPD_ID          VARCHAR2(12),
    UPD_DTTM        TIMESTAMP(6),
    CONSTRAINT PK_CUSTOMER PRIMARY KEY (CUSTOMER_ID),
    CONSTRAINT UX_CUSTOMER_MOBILE UNIQUE (MOBILE_NO),
    CONSTRAINT CK_CUSTOMER_GENDER CHECK (GENDER_CD IN ('M', 'F', 'U')),
    CONSTRAINT CK_CUSTOMER_AGREE  CHECK (AGREE_YN IN ('Y', 'N')),
    CONSTRAINT CK_CUSTOMER_USE    CHECK (USE_YN IN ('Y', 'N'))
);

CREATE INDEX SMS.IX_CUSTOMER_01 ON SMS.CUSTOMER (CUSTOMER_NM);
CREATE INDEX SMS.IX_CUSTOMER_02 ON SMS.CUSTOMER (USE_YN, REG_DTTM DESC);

COMMENT ON TABLE  SMS.CUSTOMER IS '고객 마스터. 고객별 발송 이력 조회의 기준';
COMMENT ON COLUMN SMS.CUSTOMER.CUSTOMER_ID IS '고객 PK';
COMMENT ON COLUMN SMS.CUSTOMER.CUSTOMER_NM IS '고객명';
COMMENT ON COLUMN SMS.CUSTOMER.MOBILE_NO   IS '휴대폰번호. 개인정보';
COMMENT ON COLUMN SMS.CUSTOMER.EMAIL       IS '이메일. 개인정보';
COMMENT ON COLUMN SMS.CUSTOMER.BIRTH_DT    IS '생년월일(YYYYMMDD). 개인정보';
COMMENT ON COLUMN SMS.CUSTOMER.GENDER_CD   IS '성별: M/F/U';
COMMENT ON COLUMN SMS.CUSTOMER.AGREE_YN    IS '마케팅 수신 동의 여부 Y/N';
COMMENT ON COLUMN SMS.CUSTOMER.AGREE_DT    IS '마케팅 수신 동의 일시';
COMMENT ON COLUMN SMS.CUSTOMER.MEMO        IS '메모';
COMMENT ON COLUMN SMS.CUSTOMER.USE_YN      IS '사용 여부 Y/N';
COMMENT ON COLUMN SMS.CUSTOMER.REG_ID      IS '등록자';
COMMENT ON COLUMN SMS.CUSTOMER.REG_DTTM    IS '등록 일시';
COMMENT ON COLUMN SMS.CUSTOMER.UPD_ID      IS '수정자';
COMMENT ON COLUMN SMS.CUSTOMER.UPD_DTTM    IS '수정 일시';
